server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db-config.dev.host}:${db-config.dev.port}/${db-config.dev.database}?useUnicode=true&characterEncoding=utf-8
    username: ${db-config.dev.username}
    password: ${db-config.dev.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: ${redis-config.host}
    port: ${redis-config.port}
    password: ${redis-config.password}
    database: ${redis-config.database}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB